---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart application
  ansible.builtin.systemd:
    name: employee-app
    state: restarted

- name: Verify application is running
  ansible.builtin.uri:
    url: http://localhost:8081/actuator/health
    return_content: true
  register: health_check
  until: health_check.status == 200
  retries: 10
  delay: 5
  changed_when: false
