---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - git
      - curl
      - wget
      - unzip
      - vim
      - htop
      - net-tools
      - python3-pip
    state: present

- name: Install required Python packages
  ansible.builtin.pip:
    name:
      - psycopg2-binary
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Create application user if needed
  ansible.builtin.user:
    name: "{{ app_user }}"
    shell: /bin/bash
    home: "/home/{{ app_user }}"
    state: present
  when: inventory_hostname in groups['app_servers']

- name: Setup ufw firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - "{{ '8081' if inventory_hostname in groups['app_servers'] else '5432' }}"
  notify: enable ufw
