---
- name: Deploy Employee Management Application
  hosts: app_servers
  become: true
  tasks:
    - name: Pull latest application code
      ansible.builtin.git:
        repo: "{{ app_git_repo }}"
        dest: "{{ app_source_dir }}"
        version: "{{ app_git_branch }}"
      notify: rebuild application
      become_user: "{{ app_user }}"

    - name: Ensure application service is running
      ansible.builtin.systemd:
        name: employee-app
        state: started
        enabled: true

  handlers:
    - name: Rebuild application
      ansible.builtin.command: "/opt/gradle/bin/gradle build -x test"
      args:
        chdir: "{{ app_source_dir }}"
      become_user: "{{ app_user }}"
      environment:
        JAVA_HOME: "{{ java_home }}"
      changed_when: false
      notify: restart application

    - name: Restart application
      ansible.builtin.systemd:
        name: employee-app
        state: restarted
